const translations = {
  create_group: 'Create Group',
  category: 'Category:',
  discipline: 'Discipline:',
  round: 'Round:',
  climbers: 'Climbers:',
  add_climber: 'Add Climber',
  climber_number: 'Climber Number:',
  climber_name: 'Climber Name:',
  cancel: 'Cancel',
  add: 'Add',
  download_list: 'Download List',
  download_scorecard: 'Download Scorecard',
  randomize: 'Randomize',
  create: 'Create',
  all_fields: 'Please fill in all fields',
  order: 'Order',
  climber_number_title: 'Climber Number',
  climber_name_title: 'Climber Name',
  climbers_title: 'Climbers',
  select_category: 'Select Category',
  select_discipline: 'Select Discipline',
}

module.exports = translations
