const translations = {
  group_info: '运动员组别信息',
  category: '组别:',
  discipline: '项目:',
  round: '轮次:',
  climbers: '运动员:',
  add_climber: '添加运动员',
  climber_number: '运动员参赛号码:',
  climber_name: '运动员名字:',
  cancel: '取消',
  add: '添加',
  download_list: '下载出场表',
  download_scorecard: '下载线路记录',
  randomize: '随机排序',
  edit: '编辑',
  done: '确定',
  all_fields: '请填写所有字段',
  order: '出场顺序',
  climber_number_title: '运动员参赛号码',
  climber_name_title: '运动员名字',
  select_category: '选择组别',
  select_discipline: '选择项目',
}

module.exports = translations
